name: selenium_test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  selenium_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Maven tests
        run: mvn clean test

      - name: Upload Surefire Reports (for debugging)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Load Allure test report history
        uses: actions/checkout@v4
        if: success() || failure()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Prepare Allure history
        run: |
          mkdir -p target/allure-history
          if [ -d gh-pages/allure-history ]; then
            cp -r gh-pages/allure-history target/allure-history
          fi

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Save Allure history
        run: |
          mkdir -p target/site/allure-maven-plugin/allure-history
          cp -r target/allure-history/* target/site/allure-maven-plugin/allure-history

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.EPOLIF_TOKEN }}
          publish_branch: gh-pages
          publish_dir: target/site/allure-maven-plugin
